name: test-trigger
on:
  workflow_dispatch:
permissions: write-all
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        fetch-depth: 0
    - name: config
      run: |
        git config user.name ${{ vars.SDK_USERNAME }}
        git config user.email ${{ vars.SDK_EMAIL }}
    - name: trigger
      shell: bash
      run: |
        echo "github_token: ${github_token}"
        echo "github_repo: ${github_repo}"
        echo "publish_workflows: ${publish_workflows}"
        if [ -n "$publish_workflows" ]
        then
          IFS=',' read -ra workflows <<< "$publish_workflows"
          for workflow in "${workflows[@]}"
          do
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${github_token}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "{\"ref\":\"master\"}" \
            https://api.github.com/repos/${github_repo}/actions/workflows/WORKFLOW_ID/dispatches \
            echo "workflow triggered: ${workflow}"
          done
        fi
      env:
        github_repo: ${{ github.repository }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_workflows: ${{ vars.PUBLISH_WORKFLOWS }}

